name: deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [ stable, beta, canary, madness ]
      fail-fast: false
      max-parallel: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: deploy
          fetch-depth: 0

      - name: Setup git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          name: ${{ matrix.branch }}

      - name: Copy artifacts
        run: |
          mv -f artifacts/app-release.apk ${{ matrix.branch }}/app-release.apk
          mv -f artifacts/app-debug.apk ${{ matrix.branch }}/app-debug.apk
          mv -f artifacts/stub-release.apk ${{ matrix.branch }}/stub-release.apk
          rm -r artifacts

      - name: Run helper script
        run: |
          git checkout origin/ci-management releasehelper.sh
          chmod +x releasehelper.sh
          ./releasehelper.sh ${{ matrix.branch }}
          mv -f ${{ matrix.branch }}.json docs
          mv -f note.md ${{ matrix.branch }}/note.md
          rm releasehelper.sh

      - name: Commit update
        run: |
          git restore --staged .
          git add ${{ matrix.branch }}/app-release.apk
          git add ${{ matrix.branch }}/app-debug.apk
          git add ${{ matrix.branch }}/stub-release.apk
          git add ${{ matrix.branch }}/note.md
          git add docs/${{ matrix.branch }}.json
          git commit --amend -m "Update ${{ matrix.branch }} ${{ env.VERSION }}"

      - name: Push result
        uses: ad-m/github-push-action@v0.8.0
        with:
          branch: deploy
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
